<?php

namespace Database\Seeders;


use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InmueblesSeeder extends Seeder
{
    public function run()
    {
        DB::table('inmuebles')->insert([
            // 1️⃣ CASA - Málaga
            [
                'direccion' => 'Calle 5 # 3-20',
                'titulo' => 'Casa cerca al parque principal',
                'tipoOferta' => 'venta',
                'precio' => 185000000,
                'precioAdministracion' => null,
                'area' => 120,
                'nHabitaciones' => 3,
                'nBaños' => 2,
                'nParqueaderos' => 1,
                'nPiso' => 1,
                'pisoNumero' => null,
                'descripcion' => 'Casa amplia con patio interno.',
                'estadoPublicacion' => 'disponible',
                'idUsuario' => 1,
                'idBarrio' => 1,
                'idTipoInmueble' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 2️⃣ APARTAMENTO - Concepción
            [
                'direccion' => 'Edificio Panorama, apto 302',
                'titulo' => 'Apartamento con buena iluminación',
                'tipoOferta' => 'arriendo',
                'precio' => 750000,
                'precioAdministracion' => 60000,
                'area' => 65,
                'nHabitaciones' => 2,
                'nBaños' => 1,
                'nParqueaderos' => 1,
                'nPiso' => 3,
                'pisoNumero' => 302,
                'descripcion' => 'Apartamento en zona residencial y cercana a colegios.',
                'estadoPublicacion' => 'disponible',
                'idUsuario' => 1,
                'idBarrio' => 12,
                'idTipoInmueble' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 3️⃣ LOCAL - Carcasí
            [
                'direccion' => 'Carrera 4 # 2-10',
                'titulo' => 'Local comercial central',
                'tipoOferta' => 'arriendo',
                'precio' => 500000,
                'precioAdministracion' => null,
                'area' => 20,
                'nHabitaciones' => null,
                'nBaños' => 1,
                'nParqueaderos' => null,
                'nPiso' => 1,
                'pisoNumero' => null,
                'descripcion' => 'Local ideal para miscelánea o papelería.',
                'estadoPublicacion' => 'disponible',
                'idUsuario' => 1,
                'idBarrio' => 5,
                'idTipoInmueble' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 4️⃣ CASA - Enciso
            [
                'direccion' => 'Calle 7 # 4-18',
                'titulo' => 'Casa familiar con garaje',
                'tipoOferta' => 'venta',
                'precio' => 148000000,
                'precioAdministracion' => null,
                'area' => 110,
                'nHabitaciones' => 3,
                'nBaños' => 2,
                'nParqueaderos' => 1,
                'nPiso' => 1,
                'pisoNumero' => null,
                'descripcion' => 'Casa remodelada con patio y garaje privado.',
                'estadoPublicacion' => 'disponible',
                'idUsuario' => 1,
                'idBarrio' => 15,
                'idTipoInmueble' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 5️⃣ LOTE - Macaravita
            [
                'direccion' => 'Sector Camino Real',
                'titulo' => 'Lote económico para construir',
                'tipoOferta' => 'venta',
                'precio' => 18000000,
                'precioAdministracion' => null,
                'area' => 300,
                'nHabitaciones' => null,
                'nBaños' => null,
                'nParqueaderos' => null,
                'nPiso' => null,
                'pisoNumero' => null,
                'descripcion' => 'Terreno listo para construcción.',
                'estadoPublicacion' => 'disponible',
                'idUsuario' => 1,
                'idBarrio' => 23,
                'idTipoInmueble' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 6️⃣ APARTAMENTO - San Andrés
            [
                'direccion' => 'Conjunto Residencial La Colina, apto 201',
                'titulo' => 'Apartamento en conjunto cerrado',
                'tipoOferta' => 'arriendo',
                'precio' => 850000,
                'precioAdministracion' => 90000,
                'area' => 78,
                'nHabitaciones' => 3,
                'nBaños' => 2,
                'nParqueaderos' => 1,
                'nPiso' => 2,
                'pisoNumero' => 201,
                'descripcion' => 'Apartamento moderno con balcón.',
                'estadoPublicacion' => 'disponible',
                'idUsuario' => 1,
                'idBarrio' => 27,
                'idTipoInmueble' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 7️⃣ FINCA - Guaca
            [
                'direccion' => 'Vereda El Higuerón',
                'titulo' => 'Finca productiva con frutales',
                'tipoOferta' => 'venta',
                'precio' => 220000000,
                'precioAdministracion' => null,
                'area' => 7200,
                'nHabitaciones' => 3,
                'nBaños' => 1,
                'nParqueaderos' => 2,
                'nPiso' => 1,
                'pisoNumero' => null,
                'descripcion' => 'Finca con agua natural y árboles frutales.',
                'estadoPublicacion' => 'disponible',
                'idUsuario' => 1,
                'idBarrio' => 10,
                'idTipoInmueble' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 8️⃣ CASA - Cerrito
            [
                'direccion' => 'Carrera 3 # 5-21',
                'titulo' => 'Casa tradicional',
                'tipoOferta' => 'venta',
                'precio' => 115000000,
                'precioAdministracion' => null,
                'area' => 95,
                'nHabitaciones' => 3,
                'nBaños' => 1,
                'nParqueaderos' => 1,
                'nPiso' => 1,
                'pisoNumero' => null,
                'descripcion' => 'Casa de construcción tradicional con patio interior.',
                'estadoPublicacion' => 'disponible',
                'idUsuario' => 1,
                'idBarrio' => 8,
                'idTipoInmueble' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 9️⃣ LOCAL - San Miguel
            [
                'direccion' => 'Local 12, Centro Comercial La Plaza',
                'titulo' => 'Local comercial con alto flujo',
                'tipoOferta' => 'arriendo',
                'precio' => 1200000,
                'precioAdministracion' => null,
                'area' => 35,
                'nHabitaciones' => null,
                'nBaños' => 1,
                'nParqueaderos' => null,
                'nPiso' => 1,
                'pisoNumero' => 12,
                'descripcion' => 'Local amplio ideal para restaurante o tienda.',
                'estadoPublicacion' => 'disponible',
                'idUsuario' => 1,
                'idBarrio' => 39,
                'idTipoInmueble' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 🔟 LOTE - San José de Miranda
            [
                'direccion' => 'Sector El Altico',
                'titulo' => 'Lote con vista panorámica',
                'tipoOferta' => 'venta',
                'precio' => 25000000,
                'precioAdministracion' => null,
                'area' => 350,
                'nHabitaciones' => null,
                'nBaños' => null,
                'nParqueaderos' => null,
                'nPiso' => null,
                'pisoNumero' => null,
                'descripcion' => 'Lote con excelente vista hacia la cordillera.',
                'estadoPublicacion' => 'disponible',
                'idUsuario' => 1,
                'idBarrio' => 34,
                'idTipoInmueble' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
