<?php

namespace Database\Seeders;

use App\Models\Usuario;
use Illuminate\Database\Seeder;

class UsuariosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Usuario::insert([
            [
                'nombre' => 'Juan Pérez',
                'email' => 'juanperez@gmail.com',
                'telefono' => '3104567890',
                'tipoUsuario' => 'persona',
                'nombreEmpresa' => null,
                'fechaRegistro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Inmobiliaria Los Andes',
                'email' => 'contacto@losandes.com',
                'telefono' => '3124567890',
                'tipoUsuario' => 'inmobiliaria',
                'nombreEmpresa' => 'Los Andes S.A.S',
                'fechaRegistro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'María Gómez',
                'email' => 'maria.gomez@gmail.com',
                'telefono' => '3112223344',
                'tipoUsuario' => 'persona',
                'nombreEmpresa' => null,
                'fechaRegistro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Carlos Rodríguez',
                'email' => 'carlos.rodriguez@example.com',
                'telefono' => '3001112233',
                'tipoUsuario' => 'persona',
                'nombreEmpresa' => null,
                'fechaRegistro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Inmobiliaria Málaga Hogar',
                'email' => 'info@malagahogar.com',
                'telefono' => '3145566778',
                'tipoUsuario' => 'inmobiliaria',
                'nombreEmpresa' => 'Málaga Hogar Ltda.',
                'fechaRegistro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Laura Rincón',
                'email' => 'laura.rincon@example.com',
                'telefono' => '3019988776',
                'tipoUsuario' => 'persona',
                'nombreEmpresa' => null,
                'fechaRegistro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Pedro Herrera',
                'email' => 'pedro.herrera@example.com',
                'telefono' => '3215566789',
                'tipoUsuario' => 'persona',
                'nombreEmpresa' => null,
                'fechaRegistro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Constructora Altavista',
                'email' => 'contacto@altavista.com',
                'telefono' => '3157788990',
                'tipoUsuario' => 'inmobiliaria',
                'nombreEmpresa' => 'Altavista S.A.',
                'fechaRegistro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Sofía López',
                'email' => 'sofia.lopez@example.com',
                'telefono' => '3201122334',
                'tipoUsuario' => 'persona',
                'nombreEmpresa' => null,
                'fechaRegistro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Miguel Ramírez',
                'email' => 'miguel.ramirez@example.com',
                'telefono' => '3054433221',
                'tipoUsuario' => 'persona',
                'nombreEmpresa' => null,
                'fechaRegistro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Inmobiliaria Santander Real',
                'email' => 'info@santanderreal.com',
                'telefono' => '3162211987',
                'tipoUsuario' => 'inmobiliaria',
                'nombreEmpresa' => 'Santander Real S.A.',
                'fechaRegistro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Daniela Torres',
                'email' => 'daniela.torres@example.com',
                'telefono' => '3114433556',
                'tipoUsuario' => 'persona',
                'nombreEmpresa' => null,
                'fechaRegistro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Cristian Medina',
                'email' => 'cristian.medina@example.com',
                'telefono' => '3005632289',
                'tipoUsuario' => 'persona',
                'nombreEmpresa' => null,
                'fechaRegistro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Agencia El Roble Inmobiliaria',
                'email' => 'contacto@elroble.com',
                'telefono' => '3175566771',
                'tipoUsuario' => 'inmobiliaria',
                'nombreEmpresa' => 'El Roble S.A.S',
                'fechaRegistro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Paula Suárez',
                'email' => 'paula.suarez@example.com',
                'telefono' => '3026655987',
                'tipoUsuario' => 'persona',
                'nombreEmpresa' => null,
                'fechaRegistro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Luis Herrera',
                'email' => 'luis.herrera@example.com',
                'telefono' => '3119988773',
                'tipoUsuario' => 'persona',
                'nombreEmpresa' => null,
                'fechaRegistro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Inmobiliaria Colinas del Sol',
                'email' => 'info@colinasdelsol.com',
                'telefono' => '3146677885',
                'tipoUsuario' => 'inmobiliaria',
                'nombreEmpresa' => 'Colinas del Sol SAS',
                'fechaRegistro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Esteban Vargas',
                'email' => 'esteban.vargas@example.com',
                'telefono' => '3045567889',
                'tipoUsuario' => 'persona',
                'nombreEmpresa' => null,
                'fechaRegistro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Juliana Acevedo',
                'email' => 'juliana.acevedo@example.com',
                'telefono' => '3226677889',
                'tipoUsuario' => 'persona',
                'nombreEmpresa' => null,
                'fechaRegistro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Constructora Horizonte',
                'email' => 'contacto@horizonte.com',
                'telefono' => '3197788992',
                'tipoUsuario' => 'inmobiliaria',
                'nombreEmpresa' => 'Horizonte Constructores S.A.',
                'fechaRegistro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}

